### ISSUE TITLE
verify error, number of sites not equal, after running tsdate preprocesses

### ISSUE THREAD

**Issue by stsmall** [tskit-dev/tsinfer#491]
Hi,
I am attempting to use the new version of tsdate and the new version of tsinfer. After running tsinfer without error, I ran tsdate preprocess. When I set tsinfer verify on the preprocessed trees, I received an error of "number of sites not equal". 
thanks,
@stsmall

> $ tsinfer list chrX.trees
path      = chrX.trees
size      = 519.0 MiB
edges     = 9215138
trees     = 910682
sites     = 2160904
mutations = 2124826

> $ tsinfer list chrX.pre.trees
path      = chrX.pre.trees
size      = 603.1 MiB
edges     = 11767299
trees     = 908544
sites     = 2124826
mutations = 2124826

> $ tsinfer verify chrX.samples chrX.pre.trees
2021-04-22 10:35:40,797 [47483] CRITICAL root: Traceback (most recent call last):
  File "tsinfer", line 8, in <module>
    sys.exit(main())
  File "tsinfer/__main__.py", line 5, in main
    cli.tsinfer_main()
  File "tsinfer/cli.py", line 499, in tsinfer_main
    args.runner(args)
  File "tsinfer/cli.py", line 238, in run_verify
    tsinfer.verify(samples, ts, progress_monitor=args.progress)
  File "tsinfer/inference.py", line 167, in verify
    raise ValueError("numbers of sites not equal")
ValueError: numbers of sites not equal

**Comment by stsmall** [comment]
error was resolved after removing monomorphic sites from the input vcf

**Comment by jeromekelleher** [comment]
I'm going to reopen this, as the verify code is still wrong. Thanks for the report @stsmall!

**Comment by hyanwong** [comment]
I think this is right, though isn't it? Preprocessing is meant to remove sites. So the original sample data file and the preprocessed ts should be different. Or have I misunderstood?

**Comment by hyanwong** [comment]
I guess `tsdata.preprocess_ts` should use the `filter_sites=False` param to simplify. Thinking about it, it should probably set *all* the filters to false shouldn't it, @awohns: after all, we only want to change the edge table, not anything else.

**Comment by awohns** [comment]
So right now `tsdate.preprocess_ts` will [output a warning](https://github.com/tskit-dev/tsdate/blob/af8bcd58fde1b95ff1d7d9f7bdc3f111b51af37a/tsdate/util.py#L138) if the number of sites changes, which says:

> "Different number of sites after preprocessing. Try using **{'filter_sites:' False} to avoid this"

Perhaps we can move this conversation over to `tsdate` to see if we actually want `filter_sites=False` as a default

**Comment by hyanwong** [comment]
> Perhaps we can move this conversation over to `tsdate` to see if we actually want `filter_sites=False` as a default

Yep, I think we should close this and continue the conversation in the tsdate repo.
